# permissions for end users to edit cijobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cijob-editor-role
rules:
- apiGroups:
  - objects.tinyci.org
  resources:
  - cijobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - objects.tinyci.org
  resources:
  - cijobs/status
  verbs:
  - get
